name: Turing Complete

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -S . -B ${{github.workspace}}/build 

    - name: Build Tests
      working-directory: ${{github.workspace}}/build
      run: make tests

    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: ctest -j

